"""Write docs/data_freeze.md: every record the post reads, with its sha256, size and run count.

Usage: python3 scripts/data_freeze.py [--check]

Without an option, writes docs/data_freeze.md (plan 2.8). With --check,
recomputes the hashes and lists every file that changed since the freeze: after the freeze
no arm is added, and only reruns of incomplete prompts are allowed, as dated amendments.
The git tag data-freeze-v1 is the author's to create.
"""
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GLOBS = ["results/*.json", "results/sd_variants/*.json", "collapse_lab/out/*.json",
         "collapse_lab/out/session_D/*.json",
         "collapse_lab/out/session_E/*.json", "data/*.json"]


def files():
    out = []
    for g in GLOBS:
        # post_numbers.json is derived from the others and regenerated by scripts/post_numbers.py
        out += [p for p in sorted(ROOT.glob(g)) if "backup" not in p.name and p.name != "post_numbers.json"]
    return out


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main():
    target = ROOT / "docs" / "data_freeze.md"
    if "--check" in sys.argv:
        frozen = dict(re.findall(r"^\| `([^`]+)` \| `([0-9a-f]{64})` \|", target.read_text(), flags=re.M))
        now = {str(p.relative_to(ROOT)): sha(p) for p in files()}
        changed = sorted(f for f in frozen if now.get(f) != frozen[f])
        added = sorted(set(now) - set(frozen))
        for f in changed:
            print(f"CHANGED {f}")
        for f in added:
            print(f"new     {f}")
        print(f"{len(frozen)} frozen files, {len(changed)} changed, {len(added)} new")
        return 1 if changed else 0
    rows = []
    for p in files():
        d = json.loads(p.read_text())
        n = len(d["runs"]) if isinstance(d, dict) and isinstance(d.get("runs"), list) else ""
        rows.append(f"| `{p.relative_to(ROOT)}` | `{sha(p)}` | {p.stat().st_size} | {n} |")
    target.write_text(
        f"# Data freeze\n\nWritten {datetime.now(timezone.utc).isoformat(timespec='seconds')} by "
        "`scripts/data_freeze.py`; `python3 scripts/data_freeze.py --check` lists what changed since.\n"
        "After the freeze no arm is added; reruns of incomplete prompts only, as dated amendments.\n\n"
        "| file | sha256 | bytes | runs |\n|---|---|---|---|\n" + "\n".join(rows) + "\n")
    print(f"{target.relative_to(ROOT)}: {len(rows)} files")


if __name__ == "__main__":
    sys.exit(main())
